# themes/base.py
"""
토큰 기반 렌더링 엔진.

역할 분담:
  templates/*.html  → HTML 구조 (Jinja2 템플릿)
  themes/{name}.py  → 색상·폰트 토큰 (TOKENS dict)
  themes/base.py    → 토큰 로드 + Jinja2 렌더링 (이 파일)

표준 렌더러 (classic/ink/forest 등 토큰 교체형 테마):
  render_report(), render_archive(), render_stock_report(), render_stock_archive()

커스텀 레이아웃 테마 (editorial/terminal/minimal):
  자체 render_*() 구현을 가지며, 웹 레이아웃을 Python에서 직접 정의.
  layout_html()을 헬퍼로 사용할 수 있음.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import importlib

from config.theme_config import NAV_SECTIONS, HUB_SECTIONS, FOOTER_CONFIG

_TEMPLATES = Path(__file__).parent.parent / "templates"


# ── 토큰 조회 ─────────────────────────────────────────────────────────────────

def get_tokens(theme_name: str) -> dict:
    try:
        mod = importlib.import_module(f"themes.{theme_name}")
        return mod.TOKENS
    except (ModuleNotFoundError, AttributeError):
        from themes.classic import TOKENS
        return TOKENS


# ── CSS :root 변수 블록 (테마 토큰 → CSS 변수) ────────────────────────────────

def css_root_vars(tokens: dict) -> str:
    c = tokens["colors"]
    t = tokens["typography"]
    return f"""
  :root {{
    --color-blue:        {c['blue']};
    --color-blue-light:  {c['blue_light']};
    --color-blue-50:     {c['blue_50']};
    --color-blue-200:    {c['blue_200']};
    --color-navy:        {c['navy']};
    --color-bg:          {c['bg']};
    --color-card:        {c['card']};
    --color-border:      {c['border']};
    --color-text:        {c['text']};
    --color-muted:       {c['muted']};
    --color-code-bg:     {c['code_bg']};
    --color-green:       {c['green']};
    --color-green-50:    {c.get('green_50', '#f0fdf4')};
    --color-green-200:   {c.get('green_200', '#bbf7d0')};
    --color-orange:      {c['orange']};
    --color-orange-50:   {c.get('orange_50', '#fff7ed')};
    --color-orange-200:  {c.get('orange_200', '#fed7aa')};
    --font-sans:         {t['font_sans']};
    --leading-base:      {t['leading']};
  }}"""


# ── 내비게이션 HTML ──────────────────────────────────────────────────────────

def nav_html(active_key: str, nav_prefix: str = "") -> str:
    enabled = [s for s in NAV_SECTIONS if s["enabled"]]
    parts = []
    for s in enabled:
        cls = ' class="active"' if active_key == s["key"] else ""
        parts.append(f'<a href="{nav_prefix}{s["url"]}"{cls}>{s["label"]}</a>')
    return "\n      ".join(parts)


# ── 커스텀 테마용 헬퍼 (editorial/terminal/minimal에서 사용) ──────────────────

def hub_sections_html(nav_prefix: str = "") -> str:
    active = [s for s in HUB_SECTIONS if s["enabled"]]
    if not active:
        return ""
    cards = "".join(f"""
    <a href="{nav_prefix}{s['url']}" class="hub-section-card">
      <span class="section-icon">{s['icon']}</span>
      <h3>{s['label']}</h3>
      <p>{s['desc']}</p>
    </a>""" for s in active)
    return f'<div class="hub-sections">{cards}\n  </div>'


def subscribe_card_html(subscribe_url: str) -> str:
    return f"""
  <div class="card subscribe-card">
    <h3>📬 뉴스레터 구독</h3>
    <p style="color:var(--color-muted);margin:.5em 0 0">
      매일 오전 AI가 정리한 글로벌 뉴스 브리핑을 이메일로 받아보세요.
    </p>
    <a href="{subscribe_url}" target="_blank" rel="noopener" class="btn">
      구독 신청하기
    </a>
    <p style="font-size:.8rem;color:var(--color-muted);margin:.8em 0 0">
      구독 취소는 수신된 메일 하단 링크를 클릭하세요.
    </p>
  </div>"""


def layout_html(
    title: str,
    body: str,
    active: str,
    site_title: str,
    now: str,
    tokens: dict,
    extra_css: str = "",
    nav_prefix: str = "",
) -> str:
    """커스텀 테마(minimal 등)용 레이아웃 빌더. 표준 렌더러는 Jinja2 템플릿 사용."""
    font_cdn = tokens.get("meta", {}).get("font_cdn", "")
    font_link = (
        f'<link rel="preconnect" href="https://fonts.googleapis.com">\n'
        f'  <link rel="stylesheet" href="{font_cdn}" crossorigin>'
        if font_cdn else ""
    )
    css_root = css_root_vars(tokens)
    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="AI가 매일 자동으로 수집·분석하는 글로벌 뉴스 브리핑">
  <title>{title} — {site_title}</title>
  {font_link}
  <style>
  {css_root}
  {_COMMON_CSS}
  {extra_css}
  </style>
</head>
<body>
  <header>
    <div class="logo">📰 AI <span class="accent">News</span> Brief</div>
    <nav>
      {nav_html(active, nav_prefix)}
    </nav>
  </header>

  <div class="container">
    {body}
  </div>

  <footer>
    {FOOTER_CONFIG['powered_by']} · {FOOTER_CONFIG['update_text']}<br>
    Generated by {FOOTER_CONFIG['generator']} ·
    <a href="https://github.com/{FOOTER_CONFIG['repo']}" style="color:inherit">{FOOTER_CONFIG['repo']}</a>
    · 생성: {now} KST
  </footer>
</body>
</html>"""


_COMMON_CSS = """
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: var(--font-sans);
    background: var(--color-bg);
    color: var(--color-text);
    line-height: var(--leading-base);
    -webkit-font-smoothing: antialiased;
  }
  header {
    background: var(--color-navy);
    color: #fff;
    padding: 0 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 58px;
    position: sticky; top: 0; z-index: 100;
    box-shadow: 0 2px 8px rgba(0,0,0,.25);
  }
  header .logo { font-size: 1.15rem; font-weight: 700; letter-spacing: -.3px; }
  header .logo .accent { color: var(--color-blue-light); }
  header nav a {
    color: rgba(255,255,255,.8);
    text-decoration: none;
    margin-left: 20px;
    font-size: .9rem;
    transition: color .15s;
  }
  header nav a:hover,
  header nav a.active { color: #fff; font-weight: 600; }
  .container { max-width: 860px; margin: 0 auto; padding: 36px 20px 80px; }
  .card {
    background: var(--color-card);
    border: 1px solid var(--color-border);
    border-radius: 12px;
    padding: 32px 36px;
    margin-bottom: 24px;
    box-shadow: 0 1px 4px rgba(0,0,0,.06);
  }
  h1 { font-size: 1.6rem; color: var(--color-navy); margin-bottom: 6px;
       font-weight: 700; line-height: 1.3; }
  h2 { font-size: 1.2rem; color: var(--color-blue); margin: 2em 0 .6em;
       padding-bottom: 6px; border-bottom: 2px solid var(--color-border);
       font-weight: 600; }
  h3 { font-size: 1rem; color: var(--color-navy); margin: 1.4em 0 .4em;
       font-weight: 600; }
  p  { margin-bottom: .9em; }
  a  { color: var(--color-blue); text-underline-offset: 2px; }
  ul, ol { padding-left: 1.4em; margin-bottom: .9em; }
  li { margin-bottom: .3em; }
  hr { border: none; border-top: 1px solid var(--color-border); margin: 2em 0; }
  code { background: var(--color-code-bg); padding: 2px 6px;
         border-radius: 4px; font-size: .88em; }
  blockquote {
    border-left: 4px solid var(--color-blue);
    padding: 8px 16px;
    background: var(--color-blue-50);
    border-radius: 0 8px 8px 0;
    margin: 1em 0;
    color: var(--color-muted);
  }
  mark { background: #fef08a; border-radius: 2px; padding: 0 2px; }
  .meta { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 24px; }
  .badge {
    background: var(--color-blue-50);
    color: var(--color-blue);
    border: 1px solid var(--color-blue-200);
    padding: 3px 10px;
    border-radius: 20px;
    font-size: .78rem;
    font-weight: 500;
  }
  .badge-green {
    background: var(--color-green-50);
    color: var(--color-green);
    border: 1px solid var(--color-green-200);
  }
  .badge-orange {
    background: var(--color-orange-50);
    color: var(--color-orange);
    border: 1px solid var(--color-orange-200);
  }
  .archive-list { list-style: none; padding: 0; }
  .archive-list li { border-bottom: 1px solid var(--color-border); padding: 14px 0; }
  .archive-list li:last-child { border-bottom: none; }
  .archive-list a { font-weight: 500; font-size: 1rem; text-decoration: none; }
  .archive-list a:hover { text-decoration: underline; }
  .archive-list .date { color: var(--color-muted); font-size: .85rem; margin-top: 2px; }
  .hub-sections {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 16px;
    margin-bottom: 24px;
  }
  .hub-section-card {
    background: var(--color-card);
    border: 1px solid var(--color-border);
    border-radius: 12px;
    padding: 24px;
    text-decoration: none;
    color: var(--color-text);
    transition: border-color .15s, box-shadow .15s;
    display: block;
  }
  .hub-section-card:hover {
    border-color: var(--color-blue);
    box-shadow: 0 2px 8px rgba(0,0,0,.1);
  }
  .hub-section-card .section-icon { font-size: 2rem; margin-bottom: 10px; display: block; }
  .hub-section-card h3 { color: var(--color-navy); margin: 0 0 6px; }
  .hub-section-card p { color: var(--color-muted); font-size: .9rem; margin: 0; }
  footer {
    text-align: center;
    color: var(--color-muted);
    font-size: .8rem;
    padding: 24px;
    border-top: 1px solid var(--color-border);
  }
  @media (max-width: 600px) {
    .card { padding: 20px; }
    header .logo { font-size: 1rem; }
    .hub-sections { grid-template-columns: 1fr; }
  }
"""


# ── Jinja2 환경 ───────────────────────────────────────────────────────────────

def _jinja_env():
    from jinja2 import Environment, FileSystemLoader
    return Environment(loader=FileSystemLoader(str(_TEMPLATES)), autoescape=False)


def _font_link(tokens: dict) -> str:
    cdn = tokens.get("meta", {}).get("font_cdn", "")
    if not cdn:
        return ""
    return (f'<link rel="preconnect" href="https://fonts.googleapis.com">\n'
            f'  <link rel="stylesheet" href="{cdn}" crossorigin>')


# ── 뉴스 파싱 헬퍼 ────────────────────────────────────────────────────────────

def _split_at_news_list(md_html: str) -> str:
    m = re.search(r'<h2[^>]*>.*?📋.*?수집 기사', md_html)
    if m:
        return md_html[:m.start()]
    return md_html


def _split_analysis_sections(md_html: str) -> tuple[str, str, str]:
    """md_html을 해외/국내/키워드 세 섹션으로 분리.
    Returns: (analysis_en_html, analysis_ko_html, keyword_html)
    """
    analysis = _split_at_news_list(md_html)

    en_m  = re.search(r'(<h2[^>]*>.*?🌐.*?</h2>)', analysis)
    ko_m  = re.search(r'(<h2[^>]*>.*?🇰🇷.*?</h2>)', analysis)
    kw_m  = re.search(r'(<h2[^>]*>.*?🔍.*?</h2>)', analysis)

    def _slice(start_m, end_m) -> str:
        if not start_m:
            return ""
        s = start_m.start()
        e = end_m.start() if end_m else len(analysis)
        return analysis[s:e]

    en_html  = _slice(en_m,  ko_m  or kw_m)
    ko_html  = _slice(ko_m,  kw_m)
    kw_html  = _slice(kw_m,  None)
    return en_html, ko_html, kw_html


def _build_news_list_section(news_en: list[dict], news_ko: list[dict]) -> str:
    """커스텀 테마(editorial/terminal)에서 직접 뉴스 목록 HTML이 필요할 때 사용."""
    if not news_en and not news_ko:
        return ""

    def _items(items: list[dict]) -> str:
        return "\n".join(
            f'<li><span class="news-label">{n["label"]}</span>'
            f'<a href="{n["link"]}" target="_blank" rel="noopener">{n["title"]}</a></li>'
            for n in items
        )

    en_block = (
        f'<details>\n'
        f'  <summary>🌐 영어 뉴스 ({len(news_en)}건)</summary>\n'
        f'  <ul class="news-items">{_items(news_en)}</ul>\n'
        f'</details>'
    ) if news_en else ""

    ko_block = (
        f'<details>\n'
        f'  <summary>🇰🇷 한국어 뉴스 ({len(news_ko)}건)</summary>\n'
        f'  <ul class="news-items">{_items(news_ko)}</ul>\n'
        f'</details>'
    ) if news_ko else ""

    return f"""
  <div class="card news-list-section">
    <h2>📋 수집 기사 전체 목록</h2>
    {en_block}
    {ko_block}
  </div>"""


# ── 표준 렌더러 (classic/ink/forest 등 Jinja2 템플릿 사용) ────────────────────

def render_report(ctx: dict, theme_name: str) -> str:
    tokens = get_tokens(theme_name)
    data   = ctx["data"]
    tmpl   = _jinja_env().get_template("web_news.html")
    en_html, ko_html, kw_html = _split_analysis_sections(ctx["md_html"])
    return tmpl.render(
        css_root=css_root_vars(tokens),
        font_link=_font_link(tokens),
        display_date=ctx["display_date"],
        date_str=ctx["date_str"],
        site_title=ctx["site_title"],
        now=ctx["now"],
        nav=nav_html("news"),
        stats=data["stats"],
        analysis_html=_split_at_news_list(ctx["md_html"]),
        analysis_en_html=en_html,
        analysis_ko_html=ko_html,
        keyword_section_html=kw_html,
        news_en=data.get("news_en", []),
        news_ko=data.get("news_ko", []),
        footer=FOOTER_CONFIG,
        site_url=ctx.get("site_url", ""),
    )


def render_archive(ctx: dict, theme_name: str) -> str:
    tokens = get_tokens(theme_name)
    tmpl   = _jinja_env().get_template("web_archive.html")
    return tmpl.render(
        css_root=css_root_vars(tokens),
        font_link=_font_link(tokens),
        display_date="전체 목록",
        site_title=ctx["site_title"],
        now=ctx["now"],
        nav=nav_html("archive"),
        items=ctx["items"],
        footer=FOOTER_CONFIG,
    )


def render_stock_report(ctx: dict, theme_name: str) -> str:
    tokens = get_tokens(theme_name)
    data   = ctx.get("data", {})
    temp   = data.get("temperature", {})
    level  = temp.get("level", "neutral")
    temp_class = {
        "risk_off": "temp-risk-off",
        "neutral":  "temp-neutral",
        "risk_on":  "temp-risk-on",
    }.get(level, "temp-neutral")
    tmpl = _jinja_env().get_template("web_stock.html")
    return tmpl.render(
        css_root=css_root_vars(tokens),
        font_link=_font_link(tokens),
        display_date=ctx["display_date"],
        date_str=ctx["date_str"],
        site_title=ctx["site_title"],
        now=ctx["now"],
        nav=nav_html("stock", "../"),
        md_html=ctx["md_html"],
        temp_display=temp.get("display", "🟡 중립"),
        temp_class=temp_class,
        footer=FOOTER_CONFIG,
    )


def render_stock_archive(ctx: dict, theme_name: str) -> str:
    tokens = get_tokens(theme_name)
    tmpl   = _jinja_env().get_template("web_stock_archive.html")
    return tmpl.render(
        css_root=css_root_vars(tokens),
        font_link=_font_link(tokens),
        display_date="주식 시황 전체 목록",
        site_title=ctx["site_title"],
        now=ctx["now"],
        nav=nav_html("stock", "../"),
        items=ctx["items"],
        footer=FOOTER_CONFIG,
    )
